name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm test

      - name: Generate demo JWT for contract tests
        shell: bash
        run: |
          TOKEN=$(node -e "import('./dist/lib/jwt.js').then(m=>console.log(m.signDemoJwt()))")
          echo "JWT_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Contract tests (Dredd)
        shell: bash
        run: |
          dredd ./openapi.yaml http://127.0.0.1:3000 \
            --server="npm run dev" \
            --server-wait=5 \
            --header="Authorization: Bearer $JWT_TOKEN"
